"""establish current schema baseline

Revision ID: 0001_current_schema_baseline
Revises:
Create Date: 2026-08-28 07:17:11.895413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '0001_current_schema_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the ee34b97 schema in an empty database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('admin_level', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('service_rate', sa.Float(), nullable=True),
    sa.Column('upstream_cost_rate', sa.Float(), nullable=True),
    sa.Column('service_rate_mode', sa.String(length=20), server_default='external', nullable=False),
    sa.Column('upstream_cost_rate_mode', sa.String(length=20), server_default='external', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('admin_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_action_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_action_logs_id'), ['id'], unique=False)

    op.create_table('promotion_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('company_name', sa.String(length=120), nullable=False),
    sa.Column('page_title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('cta_text', sa.String(length=80), nullable=True),
    sa.Column('cta_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=20), server_default='#2563EB', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promotion_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promotion_pages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_pages_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_pages_slug'), ['slug'], unique=True)

    op.create_table('upload_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('success_rows', sa.Integer(), nullable=True),
    sa.Column('failed_rows', sa.Integer(), nullable=True),
    sa.Column('acceptance_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_batches_id'), ['id'], unique=False)

    op.create_table('voucher_upload_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('success_files', sa.Integer(), nullable=True),
    sa.Column('duplicate_files', sa.Integer(), nullable=True),
    sa.Column('failed_files', sa.Integer(), nullable=True),
    sa.Column('total_created_reviews', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voucher_upload_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voucher_upload_batches_id'), ['id'], unique=False)

    op.create_table('business_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('business_no', sa.String(), nullable=True),
    sa.Column('public_business_no', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('plate_number', sa.String(), nullable=True),
    sa.Column('points_amount', sa.Float(), nullable=True),
    sa.Column('bank_card', sa.String(), nullable=True),
    sa.Column('record_service_rate', sa.Float(), nullable=True),
    sa.Column('record_upstream_cost_rate', sa.Float(), nullable=True),
    sa.Column('record_service_rate_mode', sa.String(length=20), server_default='external', nullable=False),
    sa.Column('record_upstream_cost_rate_mode', sa.String(length=20), server_default='external', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_records_bank_card'), ['bank_card'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_records_business_no'), ['business_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_records_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_records_plate_number'), ['plate_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_records_public_business_no'), ['public_business_no'], unique=True)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=True),
    sa.Column('related_batch_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_batch_id'], ['upload_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_related_batch_id'), ['related_batch_id'], unique=False)

    op.create_table('promotion_page_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promotion_page_id', sa.Integer(), nullable=False),
    sa.Column('image_role', sa.String(length=30), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['promotion_page_id'], ['promotion_pages.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promotion_page_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promotion_page_images_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_page_images_image_role'), ['image_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_page_images_promotion_page_id'), ['promotion_page_id'], unique=False)

    op.create_table('voucher_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('voucher_amount', sa.Float(), nullable=True),
    sa.Column('ocr_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['voucher_upload_batches.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voucher_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voucher_records_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voucher_records_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_voucher_records_id'), ['id'], unique=False)

    op.create_table('match_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.Column('business_record_id', sa.Integer(), nullable=True),
    sa.Column('match_status', sa.String(), nullable=True),
    sa.Column('name_match', sa.String(), nullable=True),
    sa.Column('bank_match', sa.String(), nullable=True),
    sa.Column('amount_match', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=True),
    sa.Column('allocation_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('primary_reviewer_id', sa.Integer(), nullable=True),
    sa.Column('primary_review_result', sa.String(), nullable=True),
    sa.Column('primary_review_comment', sa.String(), nullable=True),
    sa.Column('primary_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('secondary_reviewer_id', sa.Integer(), nullable=True),
    sa.Column('secondary_review_result', sa.String(), nullable=True),
    sa.Column('secondary_review_comment', sa.String(), nullable=True),
    sa.Column('secondary_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_record_id'], ['business_records.id'], ),
    sa.ForeignKeyConstraint(['primary_reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['secondary_reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['voucher_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_reviews_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the baseline schema; use only on disposable databases."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_reviews_id'))

    op.drop_table('match_reviews')
    with op.batch_alter_table('voucher_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voucher_records_id'))
        batch_op.drop_index(batch_op.f('ix_voucher_records_file_hash'))
        batch_op.drop_index(batch_op.f('ix_voucher_records_batch_id'))

    op.drop_table('voucher_records')
    with op.batch_alter_table('promotion_page_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotion_page_images_promotion_page_id'))
        batch_op.drop_index(batch_op.f('ix_promotion_page_images_image_role'))
        batch_op.drop_index(batch_op.f('ix_promotion_page_images_id'))

    op.drop_table('promotion_page_images')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_related_batch_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('business_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_records_public_business_no'))
        batch_op.drop_index(batch_op.f('ix_business_records_plate_number'))
        batch_op.drop_index(batch_op.f('ix_business_records_phone'))
        batch_op.drop_index(batch_op.f('ix_business_records_id'))
        batch_op.drop_index(batch_op.f('ix_business_records_business_no'))
        batch_op.drop_index(batch_op.f('ix_business_records_bank_card'))

    op.drop_table('business_records')
    with op.batch_alter_table('voucher_upload_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voucher_upload_batches_id'))

    op.drop_table('voucher_upload_batches')
    with op.batch_alter_table('upload_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_batches_id'))

    op.drop_table('upload_batches')
    with op.batch_alter_table('promotion_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotion_pages_slug'))
        batch_op.drop_index(batch_op.f('ix_promotion_pages_is_published'))
        batch_op.drop_index(batch_op.f('ix_promotion_pages_id'))

    op.drop_table('promotion_pages')
    with op.batch_alter_table('admin_action_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_action_logs_id'))

    op.drop_table('admin_action_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
